// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/checkinblindboxrecord"
)

// CheckinBlindboxRecordCreate is the builder for creating a CheckinBlindboxRecord entity.
type CheckinBlindboxRecordCreate struct {
	config
	mutation *CheckinBlindboxRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *CheckinBlindboxRecordCreate) SetUserID(v int64) *CheckinBlindboxRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPrizeItemID sets the "prize_item_id" field.
func (_c *CheckinBlindboxRecordCreate) SetPrizeItemID(v int64) *CheckinBlindboxRecordCreate {
	_c.mutation.SetPrizeItemID(v)
	return _c
}

// SetPrizeName sets the "prize_name" field.
func (_c *CheckinBlindboxRecordCreate) SetPrizeName(v string) *CheckinBlindboxRecordCreate {
	_c.mutation.SetPrizeName(v)
	return _c
}

// SetNillablePrizeName sets the "prize_name" field if the given value is not nil.
func (_c *CheckinBlindboxRecordCreate) SetNillablePrizeName(v *string) *CheckinBlindboxRecordCreate {
	if v != nil {
		_c.SetPrizeName(*v)
	}
	return _c
}

// SetRarity sets the "rarity" field.
func (_c *CheckinBlindboxRecordCreate) SetRarity(v string) *CheckinBlindboxRecordCreate {
	_c.mutation.SetRarity(v)
	return _c
}

// SetNillableRarity sets the "rarity" field if the given value is not nil.
func (_c *CheckinBlindboxRecordCreate) SetNillableRarity(v *string) *CheckinBlindboxRecordCreate {
	if v != nil {
		_c.SetRarity(*v)
	}
	return _c
}

// SetRewardType sets the "reward_type" field.
func (_c *CheckinBlindboxRecordCreate) SetRewardType(v string) *CheckinBlindboxRecordCreate {
	_c.mutation.SetRewardType(v)
	return _c
}

// SetNillableRewardType sets the "reward_type" field if the given value is not nil.
func (_c *CheckinBlindboxRecordCreate) SetNillableRewardType(v *string) *CheckinBlindboxRecordCreate {
	if v != nil {
		_c.SetRewardType(*v)
	}
	return _c
}

// SetRewardValue sets the "reward_value" field.
func (_c *CheckinBlindboxRecordCreate) SetRewardValue(v float64) *CheckinBlindboxRecordCreate {
	_c.mutation.SetRewardValue(v)
	return _c
}

// SetNillableRewardValue sets the "reward_value" field if the given value is not nil.
func (_c *CheckinBlindboxRecordCreate) SetNillableRewardValue(v *float64) *CheckinBlindboxRecordCreate {
	if v != nil {
		_c.SetRewardValue(*v)
	}
	return _c
}

// SetStreakDays sets the "streak_days" field.
func (_c *CheckinBlindboxRecordCreate) SetStreakDays(v int) *CheckinBlindboxRecordCreate {
	_c.mutation.SetStreakDays(v)
	return _c
}

// SetNillableStreakDays sets the "streak_days" field if the given value is not nil.
func (_c *CheckinBlindboxRecordCreate) SetNillableStreakDays(v *int) *CheckinBlindboxRecordCreate {
	if v != nil {
		_c.SetStreakDays(*v)
	}
	return _c
}

// SetRewardDetail sets the "reward_detail" field.
func (_c *CheckinBlindboxRecordCreate) SetRewardDetail(v string) *CheckinBlindboxRecordCreate {
	_c.mutation.SetRewardDetail(v)
	return _c
}

// SetNillableRewardDetail sets the "reward_detail" field if the given value is not nil.
func (_c *CheckinBlindboxRecordCreate) SetNillableRewardDetail(v *string) *CheckinBlindboxRecordCreate {
	if v != nil {
		_c.SetRewardDetail(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CheckinBlindboxRecordCreate) SetCreatedAt(v time.Time) *CheckinBlindboxRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CheckinBlindboxRecordCreate) SetNillableCreatedAt(v *time.Time) *CheckinBlindboxRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the CheckinBlindboxRecordMutation object of the builder.
func (_c *CheckinBlindboxRecordCreate) Mutation() *CheckinBlindboxRecordMutation {
	return _c.mutation
}

// Save creates the CheckinBlindboxRecord in the database.
func (_c *CheckinBlindboxRecordCreate) Save(ctx context.Context) (*CheckinBlindboxRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CheckinBlindboxRecordCreate) SaveX(ctx context.Context) *CheckinBlindboxRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckinBlindboxRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckinBlindboxRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CheckinBlindboxRecordCreate) defaults() {
	if _, ok := _c.mutation.PrizeName(); !ok {
		v := checkinblindboxrecord.DefaultPrizeName
		_c.mutation.SetPrizeName(v)
	}
	if _, ok := _c.mutation.Rarity(); !ok {
		v := checkinblindboxrecord.DefaultRarity
		_c.mutation.SetRarity(v)
	}
	if _, ok := _c.mutation.RewardType(); !ok {
		v := checkinblindboxrecord.DefaultRewardType
		_c.mutation.SetRewardType(v)
	}
	if _, ok := _c.mutation.RewardValue(); !ok {
		v := checkinblindboxrecord.DefaultRewardValue
		_c.mutation.SetRewardValue(v)
	}
	if _, ok := _c.mutation.StreakDays(); !ok {
		v := checkinblindboxrecord.DefaultStreakDays
		_c.mutation.SetStreakDays(v)
	}
	if _, ok := _c.mutation.RewardDetail(); !ok {
		v := checkinblindboxrecord.DefaultRewardDetail
		_c.mutation.SetRewardDetail(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := checkinblindboxrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CheckinBlindboxRecordCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CheckinBlindboxRecord.user_id"`)}
	}
	if _, ok := _c.mutation.PrizeItemID(); !ok {
		return &ValidationError{Name: "prize_item_id", err: errors.New(`ent: missing required field "CheckinBlindboxRecord.prize_item_id"`)}
	}
	if _, ok := _c.mutation.PrizeName(); !ok {
		return &ValidationError{Name: "prize_name", err: errors.New(`ent: missing required field "CheckinBlindboxRecord.prize_name"`)}
	}
	if _, ok := _c.mutation.Rarity(); !ok {
		return &ValidationError{Name: "rarity", err: errors.New(`ent: missing required field "CheckinBlindboxRecord.rarity"`)}
	}
	if _, ok := _c.mutation.RewardType(); !ok {
		return &ValidationError{Name: "reward_type", err: errors.New(`ent: missing required field "CheckinBlindboxRecord.reward_type"`)}
	}
	if _, ok := _c.mutation.RewardValue(); !ok {
		return &ValidationError{Name: "reward_value", err: errors.New(`ent: missing required field "CheckinBlindboxRecord.reward_value"`)}
	}
	if _, ok := _c.mutation.StreakDays(); !ok {
		return &ValidationError{Name: "streak_days", err: errors.New(`ent: missing required field "CheckinBlindboxRecord.streak_days"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CheckinBlindboxRecord.created_at"`)}
	}
	return nil
}

func (_c *CheckinBlindboxRecordCreate) sqlSave(ctx context.Context) (*CheckinBlindboxRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CheckinBlindboxRecordCreate) createSpec() (*CheckinBlindboxRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &CheckinBlindboxRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(checkinblindboxrecord.Table, sqlgraph.NewFieldSpec(checkinblindboxrecord.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(checkinblindboxrecord.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.PrizeItemID(); ok {
		_spec.SetField(checkinblindboxrecord.FieldPrizeItemID, field.TypeInt64, value)
		_node.PrizeItemID = value
	}
	if value, ok := _c.mutation.PrizeName(); ok {
		_spec.SetField(checkinblindboxrecord.FieldPrizeName, field.TypeString, value)
		_node.PrizeName = value
	}
	if value, ok := _c.mutation.Rarity(); ok {
		_spec.SetField(checkinblindboxrecord.FieldRarity, field.TypeString, value)
		_node.Rarity = value
	}
	if value, ok := _c.mutation.RewardType(); ok {
		_spec.SetField(checkinblindboxrecord.FieldRewardType, field.TypeString, value)
		_node.RewardType = value
	}
	if value, ok := _c.mutation.RewardValue(); ok {
		_spec.SetField(checkinblindboxrecord.FieldRewardValue, field.TypeFloat64, value)
		_node.RewardValue = value
	}
	if value, ok := _c.mutation.StreakDays(); ok {
		_spec.SetField(checkinblindboxrecord.FieldStreakDays, field.TypeInt, value)
		_node.StreakDays = value
	}
	if value, ok := _c.mutation.RewardDetail(); ok {
		_spec.SetField(checkinblindboxrecord.FieldRewardDetail, field.TypeString, value)
		_node.RewardDetail = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(checkinblindboxrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CheckinBlindboxRecord.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CheckinBlindboxRecordUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CheckinBlindboxRecordCreate) OnConflict(opts ...sql.ConflictOption) *CheckinBlindboxRecordUpsertOne {
	_c.conflict = opts
	return &CheckinBlindboxRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CheckinBlindboxRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CheckinBlindboxRecordCreate) OnConflictColumns(columns ...string) *CheckinBlindboxRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CheckinBlindboxRecordUpsertOne{
		create: _c,
	}
}

type (
	// CheckinBlindboxRecordUpsertOne is the builder for "upsert"-ing
	//  one CheckinBlindboxRecord node.
	CheckinBlindboxRecordUpsertOne struct {
		create *CheckinBlindboxRecordCreate
	}

	// CheckinBlindboxRecordUpsert is the "OnConflict" setter.
	CheckinBlindboxRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *CheckinBlindboxRecordUpsert) SetUserID(v int64) *CheckinBlindboxRecordUpsert {
	u.Set(checkinblindboxrecord.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsert) UpdateUserID() *CheckinBlindboxRecordUpsert {
	u.SetExcluded(checkinblindboxrecord.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *CheckinBlindboxRecordUpsert) AddUserID(v int64) *CheckinBlindboxRecordUpsert {
	u.Add(checkinblindboxrecord.FieldUserID, v)
	return u
}

// SetPrizeItemID sets the "prize_item_id" field.
func (u *CheckinBlindboxRecordUpsert) SetPrizeItemID(v int64) *CheckinBlindboxRecordUpsert {
	u.Set(checkinblindboxrecord.FieldPrizeItemID, v)
	return u
}

// UpdatePrizeItemID sets the "prize_item_id" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsert) UpdatePrizeItemID() *CheckinBlindboxRecordUpsert {
	u.SetExcluded(checkinblindboxrecord.FieldPrizeItemID)
	return u
}

// AddPrizeItemID adds v to the "prize_item_id" field.
func (u *CheckinBlindboxRecordUpsert) AddPrizeItemID(v int64) *CheckinBlindboxRecordUpsert {
	u.Add(checkinblindboxrecord.FieldPrizeItemID, v)
	return u
}

// SetPrizeName sets the "prize_name" field.
func (u *CheckinBlindboxRecordUpsert) SetPrizeName(v string) *CheckinBlindboxRecordUpsert {
	u.Set(checkinblindboxrecord.FieldPrizeName, v)
	return u
}

// UpdatePrizeName sets the "prize_name" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsert) UpdatePrizeName() *CheckinBlindboxRecordUpsert {
	u.SetExcluded(checkinblindboxrecord.FieldPrizeName)
	return u
}

// SetRarity sets the "rarity" field.
func (u *CheckinBlindboxRecordUpsert) SetRarity(v string) *CheckinBlindboxRecordUpsert {
	u.Set(checkinblindboxrecord.FieldRarity, v)
	return u
}

// UpdateRarity sets the "rarity" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsert) UpdateRarity() *CheckinBlindboxRecordUpsert {
	u.SetExcluded(checkinblindboxrecord.FieldRarity)
	return u
}

// SetRewardType sets the "reward_type" field.
func (u *CheckinBlindboxRecordUpsert) SetRewardType(v string) *CheckinBlindboxRecordUpsert {
	u.Set(checkinblindboxrecord.FieldRewardType, v)
	return u
}

// UpdateRewardType sets the "reward_type" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsert) UpdateRewardType() *CheckinBlindboxRecordUpsert {
	u.SetExcluded(checkinblindboxrecord.FieldRewardType)
	return u
}

// SetRewardValue sets the "reward_value" field.
func (u *CheckinBlindboxRecordUpsert) SetRewardValue(v float64) *CheckinBlindboxRecordUpsert {
	u.Set(checkinblindboxrecord.FieldRewardValue, v)
	return u
}

// UpdateRewardValue sets the "reward_value" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsert) UpdateRewardValue() *CheckinBlindboxRecordUpsert {
	u.SetExcluded(checkinblindboxrecord.FieldRewardValue)
	return u
}

// AddRewardValue adds v to the "reward_value" field.
func (u *CheckinBlindboxRecordUpsert) AddRewardValue(v float64) *CheckinBlindboxRecordUpsert {
	u.Add(checkinblindboxrecord.FieldRewardValue, v)
	return u
}

// SetStreakDays sets the "streak_days" field.
func (u *CheckinBlindboxRecordUpsert) SetStreakDays(v int) *CheckinBlindboxRecordUpsert {
	u.Set(checkinblindboxrecord.FieldStreakDays, v)
	return u
}

// UpdateStreakDays sets the "streak_days" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsert) UpdateStreakDays() *CheckinBlindboxRecordUpsert {
	u.SetExcluded(checkinblindboxrecord.FieldStreakDays)
	return u
}

// AddStreakDays adds v to the "streak_days" field.
func (u *CheckinBlindboxRecordUpsert) AddStreakDays(v int) *CheckinBlindboxRecordUpsert {
	u.Add(checkinblindboxrecord.FieldStreakDays, v)
	return u
}

// SetRewardDetail sets the "reward_detail" field.
func (u *CheckinBlindboxRecordUpsert) SetRewardDetail(v string) *CheckinBlindboxRecordUpsert {
	u.Set(checkinblindboxrecord.FieldRewardDetail, v)
	return u
}

// UpdateRewardDetail sets the "reward_detail" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsert) UpdateRewardDetail() *CheckinBlindboxRecordUpsert {
	u.SetExcluded(checkinblindboxrecord.FieldRewardDetail)
	return u
}

// ClearRewardDetail clears the value of the "reward_detail" field.
func (u *CheckinBlindboxRecordUpsert) ClearRewardDetail() *CheckinBlindboxRecordUpsert {
	u.SetNull(checkinblindboxrecord.FieldRewardDetail)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CheckinBlindboxRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CheckinBlindboxRecordUpsertOne) UpdateNewValues() *CheckinBlindboxRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(checkinblindboxrecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CheckinBlindboxRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CheckinBlindboxRecordUpsertOne) Ignore() *CheckinBlindboxRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CheckinBlindboxRecordUpsertOne) DoNothing() *CheckinBlindboxRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CheckinBlindboxRecordCreate.OnConflict
// documentation for more info.
func (u *CheckinBlindboxRecordUpsertOne) Update(set func(*CheckinBlindboxRecordUpsert)) *CheckinBlindboxRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CheckinBlindboxRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CheckinBlindboxRecordUpsertOne) SetUserID(v int64) *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CheckinBlindboxRecordUpsertOne) AddUserID(v int64) *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsertOne) UpdateUserID() *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetPrizeItemID sets the "prize_item_id" field.
func (u *CheckinBlindboxRecordUpsertOne) SetPrizeItemID(v int64) *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.SetPrizeItemID(v)
	})
}

// AddPrizeItemID adds v to the "prize_item_id" field.
func (u *CheckinBlindboxRecordUpsertOne) AddPrizeItemID(v int64) *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.AddPrizeItemID(v)
	})
}

// UpdatePrizeItemID sets the "prize_item_id" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsertOne) UpdatePrizeItemID() *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.UpdatePrizeItemID()
	})
}

// SetPrizeName sets the "prize_name" field.
func (u *CheckinBlindboxRecordUpsertOne) SetPrizeName(v string) *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.SetPrizeName(v)
	})
}

// UpdatePrizeName sets the "prize_name" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsertOne) UpdatePrizeName() *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.UpdatePrizeName()
	})
}

// SetRarity sets the "rarity" field.
func (u *CheckinBlindboxRecordUpsertOne) SetRarity(v string) *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.SetRarity(v)
	})
}

// UpdateRarity sets the "rarity" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsertOne) UpdateRarity() *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.UpdateRarity()
	})
}

// SetRewardType sets the "reward_type" field.
func (u *CheckinBlindboxRecordUpsertOne) SetRewardType(v string) *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.SetRewardType(v)
	})
}

// UpdateRewardType sets the "reward_type" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsertOne) UpdateRewardType() *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.UpdateRewardType()
	})
}

// SetRewardValue sets the "reward_value" field.
func (u *CheckinBlindboxRecordUpsertOne) SetRewardValue(v float64) *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.SetRewardValue(v)
	})
}

// AddRewardValue adds v to the "reward_value" field.
func (u *CheckinBlindboxRecordUpsertOne) AddRewardValue(v float64) *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.AddRewardValue(v)
	})
}

// UpdateRewardValue sets the "reward_value" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsertOne) UpdateRewardValue() *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.UpdateRewardValue()
	})
}

// SetStreakDays sets the "streak_days" field.
func (u *CheckinBlindboxRecordUpsertOne) SetStreakDays(v int) *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.SetStreakDays(v)
	})
}

// AddStreakDays adds v to the "streak_days" field.
func (u *CheckinBlindboxRecordUpsertOne) AddStreakDays(v int) *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.AddStreakDays(v)
	})
}

// UpdateStreakDays sets the "streak_days" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsertOne) UpdateStreakDays() *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.UpdateStreakDays()
	})
}

// SetRewardDetail sets the "reward_detail" field.
func (u *CheckinBlindboxRecordUpsertOne) SetRewardDetail(v string) *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.SetRewardDetail(v)
	})
}

// UpdateRewardDetail sets the "reward_detail" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsertOne) UpdateRewardDetail() *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.UpdateRewardDetail()
	})
}

// ClearRewardDetail clears the value of the "reward_detail" field.
func (u *CheckinBlindboxRecordUpsertOne) ClearRewardDetail() *CheckinBlindboxRecordUpsertOne {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.ClearRewardDetail()
	})
}

// Exec executes the query.
func (u *CheckinBlindboxRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CheckinBlindboxRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CheckinBlindboxRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CheckinBlindboxRecordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CheckinBlindboxRecordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CheckinBlindboxRecordCreateBulk is the builder for creating many CheckinBlindboxRecord entities in bulk.
type CheckinBlindboxRecordCreateBulk struct {
	config
	err      error
	builders []*CheckinBlindboxRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the CheckinBlindboxRecord entities in the database.
func (_c *CheckinBlindboxRecordCreateBulk) Save(ctx context.Context) ([]*CheckinBlindboxRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CheckinBlindboxRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CheckinBlindboxRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CheckinBlindboxRecordCreateBulk) SaveX(ctx context.Context) []*CheckinBlindboxRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckinBlindboxRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckinBlindboxRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CheckinBlindboxRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CheckinBlindboxRecordUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CheckinBlindboxRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *CheckinBlindboxRecordUpsertBulk {
	_c.conflict = opts
	return &CheckinBlindboxRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CheckinBlindboxRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CheckinBlindboxRecordCreateBulk) OnConflictColumns(columns ...string) *CheckinBlindboxRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CheckinBlindboxRecordUpsertBulk{
		create: _c,
	}
}

// CheckinBlindboxRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of CheckinBlindboxRecord nodes.
type CheckinBlindboxRecordUpsertBulk struct {
	create *CheckinBlindboxRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CheckinBlindboxRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CheckinBlindboxRecordUpsertBulk) UpdateNewValues() *CheckinBlindboxRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(checkinblindboxrecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CheckinBlindboxRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CheckinBlindboxRecordUpsertBulk) Ignore() *CheckinBlindboxRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CheckinBlindboxRecordUpsertBulk) DoNothing() *CheckinBlindboxRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CheckinBlindboxRecordCreateBulk.OnConflict
// documentation for more info.
func (u *CheckinBlindboxRecordUpsertBulk) Update(set func(*CheckinBlindboxRecordUpsert)) *CheckinBlindboxRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CheckinBlindboxRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CheckinBlindboxRecordUpsertBulk) SetUserID(v int64) *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CheckinBlindboxRecordUpsertBulk) AddUserID(v int64) *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsertBulk) UpdateUserID() *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetPrizeItemID sets the "prize_item_id" field.
func (u *CheckinBlindboxRecordUpsertBulk) SetPrizeItemID(v int64) *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.SetPrizeItemID(v)
	})
}

// AddPrizeItemID adds v to the "prize_item_id" field.
func (u *CheckinBlindboxRecordUpsertBulk) AddPrizeItemID(v int64) *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.AddPrizeItemID(v)
	})
}

// UpdatePrizeItemID sets the "prize_item_id" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsertBulk) UpdatePrizeItemID() *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.UpdatePrizeItemID()
	})
}

// SetPrizeName sets the "prize_name" field.
func (u *CheckinBlindboxRecordUpsertBulk) SetPrizeName(v string) *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.SetPrizeName(v)
	})
}

// UpdatePrizeName sets the "prize_name" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsertBulk) UpdatePrizeName() *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.UpdatePrizeName()
	})
}

// SetRarity sets the "rarity" field.
func (u *CheckinBlindboxRecordUpsertBulk) SetRarity(v string) *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.SetRarity(v)
	})
}

// UpdateRarity sets the "rarity" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsertBulk) UpdateRarity() *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.UpdateRarity()
	})
}

// SetRewardType sets the "reward_type" field.
func (u *CheckinBlindboxRecordUpsertBulk) SetRewardType(v string) *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.SetRewardType(v)
	})
}

// UpdateRewardType sets the "reward_type" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsertBulk) UpdateRewardType() *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.UpdateRewardType()
	})
}

// SetRewardValue sets the "reward_value" field.
func (u *CheckinBlindboxRecordUpsertBulk) SetRewardValue(v float64) *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.SetRewardValue(v)
	})
}

// AddRewardValue adds v to the "reward_value" field.
func (u *CheckinBlindboxRecordUpsertBulk) AddRewardValue(v float64) *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.AddRewardValue(v)
	})
}

// UpdateRewardValue sets the "reward_value" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsertBulk) UpdateRewardValue() *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.UpdateRewardValue()
	})
}

// SetStreakDays sets the "streak_days" field.
func (u *CheckinBlindboxRecordUpsertBulk) SetStreakDays(v int) *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.SetStreakDays(v)
	})
}

// AddStreakDays adds v to the "streak_days" field.
func (u *CheckinBlindboxRecordUpsertBulk) AddStreakDays(v int) *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.AddStreakDays(v)
	})
}

// UpdateStreakDays sets the "streak_days" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsertBulk) UpdateStreakDays() *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.UpdateStreakDays()
	})
}

// SetRewardDetail sets the "reward_detail" field.
func (u *CheckinBlindboxRecordUpsertBulk) SetRewardDetail(v string) *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.SetRewardDetail(v)
	})
}

// UpdateRewardDetail sets the "reward_detail" field to the value that was provided on create.
func (u *CheckinBlindboxRecordUpsertBulk) UpdateRewardDetail() *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.UpdateRewardDetail()
	})
}

// ClearRewardDetail clears the value of the "reward_detail" field.
func (u *CheckinBlindboxRecordUpsertBulk) ClearRewardDetail() *CheckinBlindboxRecordUpsertBulk {
	return u.Update(func(s *CheckinBlindboxRecordUpsert) {
		s.ClearRewardDetail()
	})
}

// Exec executes the query.
func (u *CheckinBlindboxRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CheckinBlindboxRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CheckinBlindboxRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CheckinBlindboxRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
