// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/checkinblindboxrecord"
)

// CheckinBlindboxRecord is the model entity for the CheckinBlindboxRecord schema.
type CheckinBlindboxRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// PrizeItemID holds the value of the "prize_item_id" field.
	PrizeItemID int64 `json:"prize_item_id,omitempty"`
	// PrizeName holds the value of the "prize_name" field.
	PrizeName string `json:"prize_name,omitempty"`
	// Rarity holds the value of the "rarity" field.
	Rarity string `json:"rarity,omitempty"`
	// RewardType holds the value of the "reward_type" field.
	RewardType string `json:"reward_type,omitempty"`
	// RewardValue holds the value of the "reward_value" field.
	RewardValue float64 `json:"reward_value,omitempty"`
	// StreakDays holds the value of the "streak_days" field.
	StreakDays int `json:"streak_days,omitempty"`
	// RewardDetail holds the value of the "reward_detail" field.
	RewardDetail string `json:"reward_detail,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CheckinBlindboxRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case checkinblindboxrecord.FieldRewardValue:
			values[i] = new(sql.NullFloat64)
		case checkinblindboxrecord.FieldID, checkinblindboxrecord.FieldUserID, checkinblindboxrecord.FieldPrizeItemID, checkinblindboxrecord.FieldStreakDays:
			values[i] = new(sql.NullInt64)
		case checkinblindboxrecord.FieldPrizeName, checkinblindboxrecord.FieldRarity, checkinblindboxrecord.FieldRewardType, checkinblindboxrecord.FieldRewardDetail:
			values[i] = new(sql.NullString)
		case checkinblindboxrecord.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CheckinBlindboxRecord fields.
func (_m *CheckinBlindboxRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case checkinblindboxrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case checkinblindboxrecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case checkinblindboxrecord.FieldPrizeItemID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prize_item_id", values[i])
			} else if value.Valid {
				_m.PrizeItemID = value.Int64
			}
		case checkinblindboxrecord.FieldPrizeName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prize_name", values[i])
			} else if value.Valid {
				_m.PrizeName = value.String
			}
		case checkinblindboxrecord.FieldRarity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rarity", values[i])
			} else if value.Valid {
				_m.Rarity = value.String
			}
		case checkinblindboxrecord.FieldRewardType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reward_type", values[i])
			} else if value.Valid {
				_m.RewardType = value.String
			}
		case checkinblindboxrecord.FieldRewardValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_value", values[i])
			} else if value.Valid {
				_m.RewardValue = value.Float64
			}
		case checkinblindboxrecord.FieldStreakDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field streak_days", values[i])
			} else if value.Valid {
				_m.StreakDays = int(value.Int64)
			}
		case checkinblindboxrecord.FieldRewardDetail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reward_detail", values[i])
			} else if value.Valid {
				_m.RewardDetail = value.String
			}
		case checkinblindboxrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CheckinBlindboxRecord.
// This includes values selected through modifiers, order, etc.
func (_m *CheckinBlindboxRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CheckinBlindboxRecord.
// Note that you need to call CheckinBlindboxRecord.Unwrap() before calling this method if this CheckinBlindboxRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CheckinBlindboxRecord) Update() *CheckinBlindboxRecordUpdateOne {
	return NewCheckinBlindboxRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CheckinBlindboxRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CheckinBlindboxRecord) Unwrap() *CheckinBlindboxRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CheckinBlindboxRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CheckinBlindboxRecord) String() string {
	var builder strings.Builder
	builder.WriteString("CheckinBlindboxRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("prize_item_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrizeItemID))
	builder.WriteString(", ")
	builder.WriteString("prize_name=")
	builder.WriteString(_m.PrizeName)
	builder.WriteString(", ")
	builder.WriteString("rarity=")
	builder.WriteString(_m.Rarity)
	builder.WriteString(", ")
	builder.WriteString("reward_type=")
	builder.WriteString(_m.RewardType)
	builder.WriteString(", ")
	builder.WriteString("reward_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardValue))
	builder.WriteString(", ")
	builder.WriteString("streak_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.StreakDays))
	builder.WriteString(", ")
	builder.WriteString("reward_detail=")
	builder.WriteString(_m.RewardDetail)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CheckinBlindboxRecords is a parsable slice of CheckinBlindboxRecord.
type CheckinBlindboxRecords []*CheckinBlindboxRecord
