// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/checkin"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CheckinCreate is the builder for creating a Checkin entity.
type CheckinCreate struct {
	config
	mutation *CheckinMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *CheckinCreate) SetUserID(v int64) *CheckinCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCheckinDate sets the "checkin_date" field.
func (_c *CheckinCreate) SetCheckinDate(v time.Time) *CheckinCreate {
	_c.mutation.SetCheckinDate(v)
	return _c
}

// SetRewardAmount sets the "reward_amount" field.
func (_c *CheckinCreate) SetRewardAmount(v float64) *CheckinCreate {
	_c.mutation.SetRewardAmount(v)
	return _c
}

// SetStreakDays sets the "streak_days" field.
func (_c *CheckinCreate) SetStreakDays(v int) *CheckinCreate {
	_c.mutation.SetStreakDays(v)
	return _c
}

// SetNillableStreakDays sets the "streak_days" field if the given value is not nil.
func (_c *CheckinCreate) SetNillableStreakDays(v *int) *CheckinCreate {
	if v != nil {
		_c.SetStreakDays(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CheckinCreate) SetCreatedAt(v time.Time) *CheckinCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CheckinCreate) SetNillableCreatedAt(v *time.Time) *CheckinCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CheckinCreate) SetUser(v *User) *CheckinCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the CheckinMutation object of the builder.
func (_c *CheckinCreate) Mutation() *CheckinMutation {
	return _c.mutation
}

// Save creates the Checkin in the database.
func (_c *CheckinCreate) Save(ctx context.Context) (*Checkin, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CheckinCreate) SaveX(ctx context.Context) *Checkin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckinCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckinCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CheckinCreate) defaults() {
	if _, ok := _c.mutation.StreakDays(); !ok {
		v := checkin.DefaultStreakDays
		_c.mutation.SetStreakDays(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := checkin.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CheckinCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Checkin.user_id"`)}
	}
	if _, ok := _c.mutation.CheckinDate(); !ok {
		return &ValidationError{Name: "checkin_date", err: errors.New(`ent: missing required field "Checkin.checkin_date"`)}
	}
	if _, ok := _c.mutation.RewardAmount(); !ok {
		return &ValidationError{Name: "reward_amount", err: errors.New(`ent: missing required field "Checkin.reward_amount"`)}
	}
	if _, ok := _c.mutation.StreakDays(); !ok {
		return &ValidationError{Name: "streak_days", err: errors.New(`ent: missing required field "Checkin.streak_days"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Checkin.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Checkin.user"`)}
	}
	return nil
}

func (_c *CheckinCreate) sqlSave(ctx context.Context) (*Checkin, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CheckinCreate) createSpec() (*Checkin, *sqlgraph.CreateSpec) {
	var (
		_node = &Checkin{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(checkin.Table, sqlgraph.NewFieldSpec(checkin.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CheckinDate(); ok {
		_spec.SetField(checkin.FieldCheckinDate, field.TypeTime, value)
		_node.CheckinDate = value
	}
	if value, ok := _c.mutation.RewardAmount(); ok {
		_spec.SetField(checkin.FieldRewardAmount, field.TypeFloat64, value)
		_node.RewardAmount = value
	}
	if value, ok := _c.mutation.StreakDays(); ok {
		_spec.SetField(checkin.FieldStreakDays, field.TypeInt, value)
		_node.StreakDays = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(checkin.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkin.UserTable,
			Columns: []string{checkin.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Checkin.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CheckinUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CheckinCreate) OnConflict(opts ...sql.ConflictOption) *CheckinUpsertOne {
	_c.conflict = opts
	return &CheckinUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Checkin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CheckinCreate) OnConflictColumns(columns ...string) *CheckinUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CheckinUpsertOne{
		create: _c,
	}
}

type (
	// CheckinUpsertOne is the builder for "upsert"-ing
	//  one Checkin node.
	CheckinUpsertOne struct {
		create *CheckinCreate
	}

	// CheckinUpsert is the "OnConflict" setter.
	CheckinUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *CheckinUpsert) SetUserID(v int64) *CheckinUpsert {
	u.Set(checkin.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckinUpsert) UpdateUserID() *CheckinUpsert {
	u.SetExcluded(checkin.FieldUserID)
	return u
}

// SetCheckinDate sets the "checkin_date" field.
func (u *CheckinUpsert) SetCheckinDate(v time.Time) *CheckinUpsert {
	u.Set(checkin.FieldCheckinDate, v)
	return u
}

// UpdateCheckinDate sets the "checkin_date" field to the value that was provided on create.
func (u *CheckinUpsert) UpdateCheckinDate() *CheckinUpsert {
	u.SetExcluded(checkin.FieldCheckinDate)
	return u
}

// SetRewardAmount sets the "reward_amount" field.
func (u *CheckinUpsert) SetRewardAmount(v float64) *CheckinUpsert {
	u.Set(checkin.FieldRewardAmount, v)
	return u
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *CheckinUpsert) UpdateRewardAmount() *CheckinUpsert {
	u.SetExcluded(checkin.FieldRewardAmount)
	return u
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *CheckinUpsert) AddRewardAmount(v float64) *CheckinUpsert {
	u.Add(checkin.FieldRewardAmount, v)
	return u
}

// SetStreakDays sets the "streak_days" field.
func (u *CheckinUpsert) SetStreakDays(v int) *CheckinUpsert {
	u.Set(checkin.FieldStreakDays, v)
	return u
}

// UpdateStreakDays sets the "streak_days" field to the value that was provided on create.
func (u *CheckinUpsert) UpdateStreakDays() *CheckinUpsert {
	u.SetExcluded(checkin.FieldStreakDays)
	return u
}

// AddStreakDays adds v to the "streak_days" field.
func (u *CheckinUpsert) AddStreakDays(v int) *CheckinUpsert {
	u.Add(checkin.FieldStreakDays, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Checkin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CheckinUpsertOne) UpdateNewValues() *CheckinUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(checkin.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Checkin.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CheckinUpsertOne) Ignore() *CheckinUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CheckinUpsertOne) DoNothing() *CheckinUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CheckinCreate.OnConflict
// documentation for more info.
func (u *CheckinUpsertOne) Update(set func(*CheckinUpsert)) *CheckinUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CheckinUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CheckinUpsertOne) SetUserID(v int64) *CheckinUpsertOne {
	return u.Update(func(s *CheckinUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckinUpsertOne) UpdateUserID() *CheckinUpsertOne {
	return u.Update(func(s *CheckinUpsert) {
		s.UpdateUserID()
	})
}

// SetCheckinDate sets the "checkin_date" field.
func (u *CheckinUpsertOne) SetCheckinDate(v time.Time) *CheckinUpsertOne {
	return u.Update(func(s *CheckinUpsert) {
		s.SetCheckinDate(v)
	})
}

// UpdateCheckinDate sets the "checkin_date" field to the value that was provided on create.
func (u *CheckinUpsertOne) UpdateCheckinDate() *CheckinUpsertOne {
	return u.Update(func(s *CheckinUpsert) {
		s.UpdateCheckinDate()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *CheckinUpsertOne) SetRewardAmount(v float64) *CheckinUpsertOne {
	return u.Update(func(s *CheckinUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *CheckinUpsertOne) AddRewardAmount(v float64) *CheckinUpsertOne {
	return u.Update(func(s *CheckinUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *CheckinUpsertOne) UpdateRewardAmount() *CheckinUpsertOne {
	return u.Update(func(s *CheckinUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetStreakDays sets the "streak_days" field.
func (u *CheckinUpsertOne) SetStreakDays(v int) *CheckinUpsertOne {
	return u.Update(func(s *CheckinUpsert) {
		s.SetStreakDays(v)
	})
}

// AddStreakDays adds v to the "streak_days" field.
func (u *CheckinUpsertOne) AddStreakDays(v int) *CheckinUpsertOne {
	return u.Update(func(s *CheckinUpsert) {
		s.AddStreakDays(v)
	})
}

// UpdateStreakDays sets the "streak_days" field to the value that was provided on create.
func (u *CheckinUpsertOne) UpdateStreakDays() *CheckinUpsertOne {
	return u.Update(func(s *CheckinUpsert) {
		s.UpdateStreakDays()
	})
}

// Exec executes the query.
func (u *CheckinUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CheckinCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CheckinUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CheckinUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CheckinUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CheckinCreateBulk is the builder for creating many Checkin entities in bulk.
type CheckinCreateBulk struct {
	config
	err      error
	builders []*CheckinCreate
	conflict []sql.ConflictOption
}

// Save creates the Checkin entities in the database.
func (_c *CheckinCreateBulk) Save(ctx context.Context) ([]*Checkin, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Checkin, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CheckinMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CheckinCreateBulk) SaveX(ctx context.Context) []*Checkin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckinCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckinCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Checkin.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CheckinUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CheckinCreateBulk) OnConflict(opts ...sql.ConflictOption) *CheckinUpsertBulk {
	_c.conflict = opts
	return &CheckinUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Checkin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CheckinCreateBulk) OnConflictColumns(columns ...string) *CheckinUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CheckinUpsertBulk{
		create: _c,
	}
}

// CheckinUpsertBulk is the builder for "upsert"-ing
// a bulk of Checkin nodes.
type CheckinUpsertBulk struct {
	create *CheckinCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Checkin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CheckinUpsertBulk) UpdateNewValues() *CheckinUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(checkin.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Checkin.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CheckinUpsertBulk) Ignore() *CheckinUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CheckinUpsertBulk) DoNothing() *CheckinUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CheckinCreateBulk.OnConflict
// documentation for more info.
func (u *CheckinUpsertBulk) Update(set func(*CheckinUpsert)) *CheckinUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CheckinUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CheckinUpsertBulk) SetUserID(v int64) *CheckinUpsertBulk {
	return u.Update(func(s *CheckinUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckinUpsertBulk) UpdateUserID() *CheckinUpsertBulk {
	return u.Update(func(s *CheckinUpsert) {
		s.UpdateUserID()
	})
}

// SetCheckinDate sets the "checkin_date" field.
func (u *CheckinUpsertBulk) SetCheckinDate(v time.Time) *CheckinUpsertBulk {
	return u.Update(func(s *CheckinUpsert) {
		s.SetCheckinDate(v)
	})
}

// UpdateCheckinDate sets the "checkin_date" field to the value that was provided on create.
func (u *CheckinUpsertBulk) UpdateCheckinDate() *CheckinUpsertBulk {
	return u.Update(func(s *CheckinUpsert) {
		s.UpdateCheckinDate()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *CheckinUpsertBulk) SetRewardAmount(v float64) *CheckinUpsertBulk {
	return u.Update(func(s *CheckinUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *CheckinUpsertBulk) AddRewardAmount(v float64) *CheckinUpsertBulk {
	return u.Update(func(s *CheckinUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *CheckinUpsertBulk) UpdateRewardAmount() *CheckinUpsertBulk {
	return u.Update(func(s *CheckinUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetStreakDays sets the "streak_days" field.
func (u *CheckinUpsertBulk) SetStreakDays(v int) *CheckinUpsertBulk {
	return u.Update(func(s *CheckinUpsert) {
		s.SetStreakDays(v)
	})
}

// AddStreakDays adds v to the "streak_days" field.
func (u *CheckinUpsertBulk) AddStreakDays(v int) *CheckinUpsertBulk {
	return u.Update(func(s *CheckinUpsert) {
		s.AddStreakDays(v)
	})
}

// UpdateStreakDays sets the "streak_days" field to the value that was provided on create.
func (u *CheckinUpsertBulk) UpdateStreakDays() *CheckinUpsertBulk {
	return u.Update(func(s *CheckinUpsert) {
		s.UpdateStreakDays()
	})
}

// Exec executes the query.
func (u *CheckinUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CheckinCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CheckinCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CheckinUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
