// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/checkinblindboxrecord"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CheckinBlindboxRecordUpdate is the builder for updating CheckinBlindboxRecord entities.
type CheckinBlindboxRecordUpdate struct {
	config
	hooks    []Hook
	mutation *CheckinBlindboxRecordMutation
}

// Where appends a list predicates to the CheckinBlindboxRecordUpdate builder.
func (_u *CheckinBlindboxRecordUpdate) Where(ps ...predicate.CheckinBlindboxRecord) *CheckinBlindboxRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CheckinBlindboxRecordUpdate) SetUserID(v int64) *CheckinBlindboxRecordUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CheckinBlindboxRecordUpdate) SetNillableUserID(v *int64) *CheckinBlindboxRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CheckinBlindboxRecordUpdate) AddUserID(v int64) *CheckinBlindboxRecordUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPrizeItemID sets the "prize_item_id" field.
func (_u *CheckinBlindboxRecordUpdate) SetPrizeItemID(v int64) *CheckinBlindboxRecordUpdate {
	_u.mutation.ResetPrizeItemID()
	_u.mutation.SetPrizeItemID(v)
	return _u
}

// SetNillablePrizeItemID sets the "prize_item_id" field if the given value is not nil.
func (_u *CheckinBlindboxRecordUpdate) SetNillablePrizeItemID(v *int64) *CheckinBlindboxRecordUpdate {
	if v != nil {
		_u.SetPrizeItemID(*v)
	}
	return _u
}

// AddPrizeItemID adds value to the "prize_item_id" field.
func (_u *CheckinBlindboxRecordUpdate) AddPrizeItemID(v int64) *CheckinBlindboxRecordUpdate {
	_u.mutation.AddPrizeItemID(v)
	return _u
}

// SetPrizeName sets the "prize_name" field.
func (_u *CheckinBlindboxRecordUpdate) SetPrizeName(v string) *CheckinBlindboxRecordUpdate {
	_u.mutation.SetPrizeName(v)
	return _u
}

// SetNillablePrizeName sets the "prize_name" field if the given value is not nil.
func (_u *CheckinBlindboxRecordUpdate) SetNillablePrizeName(v *string) *CheckinBlindboxRecordUpdate {
	if v != nil {
		_u.SetPrizeName(*v)
	}
	return _u
}

// SetRarity sets the "rarity" field.
func (_u *CheckinBlindboxRecordUpdate) SetRarity(v string) *CheckinBlindboxRecordUpdate {
	_u.mutation.SetRarity(v)
	return _u
}

// SetNillableRarity sets the "rarity" field if the given value is not nil.
func (_u *CheckinBlindboxRecordUpdate) SetNillableRarity(v *string) *CheckinBlindboxRecordUpdate {
	if v != nil {
		_u.SetRarity(*v)
	}
	return _u
}

// SetRewardType sets the "reward_type" field.
func (_u *CheckinBlindboxRecordUpdate) SetRewardType(v string) *CheckinBlindboxRecordUpdate {
	_u.mutation.SetRewardType(v)
	return _u
}

// SetNillableRewardType sets the "reward_type" field if the given value is not nil.
func (_u *CheckinBlindboxRecordUpdate) SetNillableRewardType(v *string) *CheckinBlindboxRecordUpdate {
	if v != nil {
		_u.SetRewardType(*v)
	}
	return _u
}

// SetRewardValue sets the "reward_value" field.
func (_u *CheckinBlindboxRecordUpdate) SetRewardValue(v float64) *CheckinBlindboxRecordUpdate {
	_u.mutation.ResetRewardValue()
	_u.mutation.SetRewardValue(v)
	return _u
}

// SetNillableRewardValue sets the "reward_value" field if the given value is not nil.
func (_u *CheckinBlindboxRecordUpdate) SetNillableRewardValue(v *float64) *CheckinBlindboxRecordUpdate {
	if v != nil {
		_u.SetRewardValue(*v)
	}
	return _u
}

// AddRewardValue adds value to the "reward_value" field.
func (_u *CheckinBlindboxRecordUpdate) AddRewardValue(v float64) *CheckinBlindboxRecordUpdate {
	_u.mutation.AddRewardValue(v)
	return _u
}

// SetStreakDays sets the "streak_days" field.
func (_u *CheckinBlindboxRecordUpdate) SetStreakDays(v int) *CheckinBlindboxRecordUpdate {
	_u.mutation.ResetStreakDays()
	_u.mutation.SetStreakDays(v)
	return _u
}

// SetNillableStreakDays sets the "streak_days" field if the given value is not nil.
func (_u *CheckinBlindboxRecordUpdate) SetNillableStreakDays(v *int) *CheckinBlindboxRecordUpdate {
	if v != nil {
		_u.SetStreakDays(*v)
	}
	return _u
}

// AddStreakDays adds value to the "streak_days" field.
func (_u *CheckinBlindboxRecordUpdate) AddStreakDays(v int) *CheckinBlindboxRecordUpdate {
	_u.mutation.AddStreakDays(v)
	return _u
}

// SetRewardDetail sets the "reward_detail" field.
func (_u *CheckinBlindboxRecordUpdate) SetRewardDetail(v string) *CheckinBlindboxRecordUpdate {
	_u.mutation.SetRewardDetail(v)
	return _u
}

// SetNillableRewardDetail sets the "reward_detail" field if the given value is not nil.
func (_u *CheckinBlindboxRecordUpdate) SetNillableRewardDetail(v *string) *CheckinBlindboxRecordUpdate {
	if v != nil {
		_u.SetRewardDetail(*v)
	}
	return _u
}

// ClearRewardDetail clears the value of the "reward_detail" field.
func (_u *CheckinBlindboxRecordUpdate) ClearRewardDetail() *CheckinBlindboxRecordUpdate {
	_u.mutation.ClearRewardDetail()
	return _u
}

// Mutation returns the CheckinBlindboxRecordMutation object of the builder.
func (_u *CheckinBlindboxRecordUpdate) Mutation() *CheckinBlindboxRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CheckinBlindboxRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckinBlindboxRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CheckinBlindboxRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckinBlindboxRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CheckinBlindboxRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(checkinblindboxrecord.Table, checkinblindboxrecord.Columns, sqlgraph.NewFieldSpec(checkinblindboxrecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(checkinblindboxrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(checkinblindboxrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PrizeItemID(); ok {
		_spec.SetField(checkinblindboxrecord.FieldPrizeItemID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrizeItemID(); ok {
		_spec.AddField(checkinblindboxrecord.FieldPrizeItemID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PrizeName(); ok {
		_spec.SetField(checkinblindboxrecord.FieldPrizeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rarity(); ok {
		_spec.SetField(checkinblindboxrecord.FieldRarity, field.TypeString, value)
	}
	if value, ok := _u.mutation.RewardType(); ok {
		_spec.SetField(checkinblindboxrecord.FieldRewardType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RewardValue(); ok {
		_spec.SetField(checkinblindboxrecord.FieldRewardValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardValue(); ok {
		_spec.AddField(checkinblindboxrecord.FieldRewardValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StreakDays(); ok {
		_spec.SetField(checkinblindboxrecord.FieldStreakDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStreakDays(); ok {
		_spec.AddField(checkinblindboxrecord.FieldStreakDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RewardDetail(); ok {
		_spec.SetField(checkinblindboxrecord.FieldRewardDetail, field.TypeString, value)
	}
	if _u.mutation.RewardDetailCleared() {
		_spec.ClearField(checkinblindboxrecord.FieldRewardDetail, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkinblindboxrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CheckinBlindboxRecordUpdateOne is the builder for updating a single CheckinBlindboxRecord entity.
type CheckinBlindboxRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CheckinBlindboxRecordMutation
}

// SetUserID sets the "user_id" field.
func (_u *CheckinBlindboxRecordUpdateOne) SetUserID(v int64) *CheckinBlindboxRecordUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CheckinBlindboxRecordUpdateOne) SetNillableUserID(v *int64) *CheckinBlindboxRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CheckinBlindboxRecordUpdateOne) AddUserID(v int64) *CheckinBlindboxRecordUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPrizeItemID sets the "prize_item_id" field.
func (_u *CheckinBlindboxRecordUpdateOne) SetPrizeItemID(v int64) *CheckinBlindboxRecordUpdateOne {
	_u.mutation.ResetPrizeItemID()
	_u.mutation.SetPrizeItemID(v)
	return _u
}

// SetNillablePrizeItemID sets the "prize_item_id" field if the given value is not nil.
func (_u *CheckinBlindboxRecordUpdateOne) SetNillablePrizeItemID(v *int64) *CheckinBlindboxRecordUpdateOne {
	if v != nil {
		_u.SetPrizeItemID(*v)
	}
	return _u
}

// AddPrizeItemID adds value to the "prize_item_id" field.
func (_u *CheckinBlindboxRecordUpdateOne) AddPrizeItemID(v int64) *CheckinBlindboxRecordUpdateOne {
	_u.mutation.AddPrizeItemID(v)
	return _u
}

// SetPrizeName sets the "prize_name" field.
func (_u *CheckinBlindboxRecordUpdateOne) SetPrizeName(v string) *CheckinBlindboxRecordUpdateOne {
	_u.mutation.SetPrizeName(v)
	return _u
}

// SetNillablePrizeName sets the "prize_name" field if the given value is not nil.
func (_u *CheckinBlindboxRecordUpdateOne) SetNillablePrizeName(v *string) *CheckinBlindboxRecordUpdateOne {
	if v != nil {
		_u.SetPrizeName(*v)
	}
	return _u
}

// SetRarity sets the "rarity" field.
func (_u *CheckinBlindboxRecordUpdateOne) SetRarity(v string) *CheckinBlindboxRecordUpdateOne {
	_u.mutation.SetRarity(v)
	return _u
}

// SetNillableRarity sets the "rarity" field if the given value is not nil.
func (_u *CheckinBlindboxRecordUpdateOne) SetNillableRarity(v *string) *CheckinBlindboxRecordUpdateOne {
	if v != nil {
		_u.SetRarity(*v)
	}
	return _u
}

// SetRewardType sets the "reward_type" field.
func (_u *CheckinBlindboxRecordUpdateOne) SetRewardType(v string) *CheckinBlindboxRecordUpdateOne {
	_u.mutation.SetRewardType(v)
	return _u
}

// SetNillableRewardType sets the "reward_type" field if the given value is not nil.
func (_u *CheckinBlindboxRecordUpdateOne) SetNillableRewardType(v *string) *CheckinBlindboxRecordUpdateOne {
	if v != nil {
		_u.SetRewardType(*v)
	}
	return _u
}

// SetRewardValue sets the "reward_value" field.
func (_u *CheckinBlindboxRecordUpdateOne) SetRewardValue(v float64) *CheckinBlindboxRecordUpdateOne {
	_u.mutation.ResetRewardValue()
	_u.mutation.SetRewardValue(v)
	return _u
}

// SetNillableRewardValue sets the "reward_value" field if the given value is not nil.
func (_u *CheckinBlindboxRecordUpdateOne) SetNillableRewardValue(v *float64) *CheckinBlindboxRecordUpdateOne {
	if v != nil {
		_u.SetRewardValue(*v)
	}
	return _u
}

// AddRewardValue adds value to the "reward_value" field.
func (_u *CheckinBlindboxRecordUpdateOne) AddRewardValue(v float64) *CheckinBlindboxRecordUpdateOne {
	_u.mutation.AddRewardValue(v)
	return _u
}

// SetStreakDays sets the "streak_days" field.
func (_u *CheckinBlindboxRecordUpdateOne) SetStreakDays(v int) *CheckinBlindboxRecordUpdateOne {
	_u.mutation.ResetStreakDays()
	_u.mutation.SetStreakDays(v)
	return _u
}

// SetNillableStreakDays sets the "streak_days" field if the given value is not nil.
func (_u *CheckinBlindboxRecordUpdateOne) SetNillableStreakDays(v *int) *CheckinBlindboxRecordUpdateOne {
	if v != nil {
		_u.SetStreakDays(*v)
	}
	return _u
}

// AddStreakDays adds value to the "streak_days" field.
func (_u *CheckinBlindboxRecordUpdateOne) AddStreakDays(v int) *CheckinBlindboxRecordUpdateOne {
	_u.mutation.AddStreakDays(v)
	return _u
}

// SetRewardDetail sets the "reward_detail" field.
func (_u *CheckinBlindboxRecordUpdateOne) SetRewardDetail(v string) *CheckinBlindboxRecordUpdateOne {
	_u.mutation.SetRewardDetail(v)
	return _u
}

// SetNillableRewardDetail sets the "reward_detail" field if the given value is not nil.
func (_u *CheckinBlindboxRecordUpdateOne) SetNillableRewardDetail(v *string) *CheckinBlindboxRecordUpdateOne {
	if v != nil {
		_u.SetRewardDetail(*v)
	}
	return _u
}

// ClearRewardDetail clears the value of the "reward_detail" field.
func (_u *CheckinBlindboxRecordUpdateOne) ClearRewardDetail() *CheckinBlindboxRecordUpdateOne {
	_u.mutation.ClearRewardDetail()
	return _u
}

// Mutation returns the CheckinBlindboxRecordMutation object of the builder.
func (_u *CheckinBlindboxRecordUpdateOne) Mutation() *CheckinBlindboxRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the CheckinBlindboxRecordUpdate builder.
func (_u *CheckinBlindboxRecordUpdateOne) Where(ps ...predicate.CheckinBlindboxRecord) *CheckinBlindboxRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CheckinBlindboxRecordUpdateOne) Select(field string, fields ...string) *CheckinBlindboxRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CheckinBlindboxRecord entity.
func (_u *CheckinBlindboxRecordUpdateOne) Save(ctx context.Context) (*CheckinBlindboxRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckinBlindboxRecordUpdateOne) SaveX(ctx context.Context) *CheckinBlindboxRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CheckinBlindboxRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckinBlindboxRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CheckinBlindboxRecordUpdateOne) sqlSave(ctx context.Context) (_node *CheckinBlindboxRecord, err error) {
	_spec := sqlgraph.NewUpdateSpec(checkinblindboxrecord.Table, checkinblindboxrecord.Columns, sqlgraph.NewFieldSpec(checkinblindboxrecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CheckinBlindboxRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkinblindboxrecord.FieldID)
		for _, f := range fields {
			if !checkinblindboxrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checkinblindboxrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(checkinblindboxrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(checkinblindboxrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PrizeItemID(); ok {
		_spec.SetField(checkinblindboxrecord.FieldPrizeItemID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrizeItemID(); ok {
		_spec.AddField(checkinblindboxrecord.FieldPrizeItemID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PrizeName(); ok {
		_spec.SetField(checkinblindboxrecord.FieldPrizeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rarity(); ok {
		_spec.SetField(checkinblindboxrecord.FieldRarity, field.TypeString, value)
	}
	if value, ok := _u.mutation.RewardType(); ok {
		_spec.SetField(checkinblindboxrecord.FieldRewardType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RewardValue(); ok {
		_spec.SetField(checkinblindboxrecord.FieldRewardValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardValue(); ok {
		_spec.AddField(checkinblindboxrecord.FieldRewardValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StreakDays(); ok {
		_spec.SetField(checkinblindboxrecord.FieldStreakDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStreakDays(); ok {
		_spec.AddField(checkinblindboxrecord.FieldStreakDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RewardDetail(); ok {
		_spec.SetField(checkinblindboxrecord.FieldRewardDetail, field.TypeString, value)
	}
	if _u.mutation.RewardDetailCleared() {
		_spec.ClearField(checkinblindboxrecord.FieldRewardDetail, field.TypeString)
	}
	_node = &CheckinBlindboxRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkinblindboxrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
