// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/checkin"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CheckinUpdate is the builder for updating Checkin entities.
type CheckinUpdate struct {
	config
	hooks    []Hook
	mutation *CheckinMutation
}

// Where appends a list predicates to the CheckinUpdate builder.
func (_u *CheckinUpdate) Where(ps ...predicate.Checkin) *CheckinUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CheckinUpdate) SetUserID(v int64) *CheckinUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CheckinUpdate) SetNillableUserID(v *int64) *CheckinUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCheckinDate sets the "checkin_date" field.
func (_u *CheckinUpdate) SetCheckinDate(v time.Time) *CheckinUpdate {
	_u.mutation.SetCheckinDate(v)
	return _u
}

// SetNillableCheckinDate sets the "checkin_date" field if the given value is not nil.
func (_u *CheckinUpdate) SetNillableCheckinDate(v *time.Time) *CheckinUpdate {
	if v != nil {
		_u.SetCheckinDate(*v)
	}
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *CheckinUpdate) SetRewardAmount(v float64) *CheckinUpdate {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *CheckinUpdate) SetNillableRewardAmount(v *float64) *CheckinUpdate {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *CheckinUpdate) AddRewardAmount(v float64) *CheckinUpdate {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetStreakDays sets the "streak_days" field.
func (_u *CheckinUpdate) SetStreakDays(v int) *CheckinUpdate {
	_u.mutation.ResetStreakDays()
	_u.mutation.SetStreakDays(v)
	return _u
}

// SetNillableStreakDays sets the "streak_days" field if the given value is not nil.
func (_u *CheckinUpdate) SetNillableStreakDays(v *int) *CheckinUpdate {
	if v != nil {
		_u.SetStreakDays(*v)
	}
	return _u
}

// AddStreakDays adds value to the "streak_days" field.
func (_u *CheckinUpdate) AddStreakDays(v int) *CheckinUpdate {
	_u.mutation.AddStreakDays(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CheckinUpdate) SetUser(v *User) *CheckinUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CheckinMutation object of the builder.
func (_u *CheckinUpdate) Mutation() *CheckinMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CheckinUpdate) ClearUser() *CheckinUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CheckinUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckinUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CheckinUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckinUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckinUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Checkin.user"`)
	}
	return nil
}

func (_u *CheckinUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkin.Table, checkin.Columns, sqlgraph.NewFieldSpec(checkin.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CheckinDate(); ok {
		_spec.SetField(checkin.FieldCheckinDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(checkin.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(checkin.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StreakDays(); ok {
		_spec.SetField(checkin.FieldStreakDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStreakDays(); ok {
		_spec.AddField(checkin.FieldStreakDays, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkin.UserTable,
			Columns: []string{checkin.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkin.UserTable,
			Columns: []string{checkin.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CheckinUpdateOne is the builder for updating a single Checkin entity.
type CheckinUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CheckinMutation
}

// SetUserID sets the "user_id" field.
func (_u *CheckinUpdateOne) SetUserID(v int64) *CheckinUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CheckinUpdateOne) SetNillableUserID(v *int64) *CheckinUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCheckinDate sets the "checkin_date" field.
func (_u *CheckinUpdateOne) SetCheckinDate(v time.Time) *CheckinUpdateOne {
	_u.mutation.SetCheckinDate(v)
	return _u
}

// SetNillableCheckinDate sets the "checkin_date" field if the given value is not nil.
func (_u *CheckinUpdateOne) SetNillableCheckinDate(v *time.Time) *CheckinUpdateOne {
	if v != nil {
		_u.SetCheckinDate(*v)
	}
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *CheckinUpdateOne) SetRewardAmount(v float64) *CheckinUpdateOne {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *CheckinUpdateOne) SetNillableRewardAmount(v *float64) *CheckinUpdateOne {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *CheckinUpdateOne) AddRewardAmount(v float64) *CheckinUpdateOne {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetStreakDays sets the "streak_days" field.
func (_u *CheckinUpdateOne) SetStreakDays(v int) *CheckinUpdateOne {
	_u.mutation.ResetStreakDays()
	_u.mutation.SetStreakDays(v)
	return _u
}

// SetNillableStreakDays sets the "streak_days" field if the given value is not nil.
func (_u *CheckinUpdateOne) SetNillableStreakDays(v *int) *CheckinUpdateOne {
	if v != nil {
		_u.SetStreakDays(*v)
	}
	return _u
}

// AddStreakDays adds value to the "streak_days" field.
func (_u *CheckinUpdateOne) AddStreakDays(v int) *CheckinUpdateOne {
	_u.mutation.AddStreakDays(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CheckinUpdateOne) SetUser(v *User) *CheckinUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CheckinMutation object of the builder.
func (_u *CheckinUpdateOne) Mutation() *CheckinMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CheckinUpdateOne) ClearUser() *CheckinUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the CheckinUpdate builder.
func (_u *CheckinUpdateOne) Where(ps ...predicate.Checkin) *CheckinUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CheckinUpdateOne) Select(field string, fields ...string) *CheckinUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Checkin entity.
func (_u *CheckinUpdateOne) Save(ctx context.Context) (*Checkin, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckinUpdateOne) SaveX(ctx context.Context) *Checkin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CheckinUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckinUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckinUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Checkin.user"`)
	}
	return nil
}

func (_u *CheckinUpdateOne) sqlSave(ctx context.Context) (_node *Checkin, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkin.Table, checkin.Columns, sqlgraph.NewFieldSpec(checkin.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Checkin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkin.FieldID)
		for _, f := range fields {
			if !checkin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checkin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CheckinDate(); ok {
		_spec.SetField(checkin.FieldCheckinDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(checkin.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(checkin.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StreakDays(); ok {
		_spec.SetField(checkin.FieldStreakDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStreakDays(); ok {
		_spec.AddField(checkin.FieldStreakDays, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkin.UserTable,
			Columns: []string{checkin.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkin.UserTable,
			Columns: []string{checkin.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Checkin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
