// Code generated by ent, DO NOT EDIT.

package checkin

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Checkin {
	return predicate.Checkin(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Checkin {
	return predicate.Checkin(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Checkin {
	return predicate.Checkin(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Checkin {
	return predicate.Checkin(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Checkin {
	return predicate.Checkin(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Checkin {
	return predicate.Checkin(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Checkin {
	return predicate.Checkin(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Checkin {
	return predicate.Checkin(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Checkin {
	return predicate.Checkin(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Checkin {
	return predicate.Checkin(sql.FieldEQ(FieldUserID, v))
}

// CheckinDate applies equality check predicate on the "checkin_date" field. It's identical to CheckinDateEQ.
func CheckinDate(v time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldEQ(FieldCheckinDate, v))
}

// RewardAmount applies equality check predicate on the "reward_amount" field. It's identical to RewardAmountEQ.
func RewardAmount(v float64) predicate.Checkin {
	return predicate.Checkin(sql.FieldEQ(FieldRewardAmount, v))
}

// StreakDays applies equality check predicate on the "streak_days" field. It's identical to StreakDaysEQ.
func StreakDays(v int) predicate.Checkin {
	return predicate.Checkin(sql.FieldEQ(FieldStreakDays, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Checkin {
	return predicate.Checkin(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Checkin {
	return predicate.Checkin(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Checkin {
	return predicate.Checkin(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Checkin {
	return predicate.Checkin(sql.FieldNotIn(FieldUserID, vs...))
}

// CheckinDateEQ applies the EQ predicate on the "checkin_date" field.
func CheckinDateEQ(v time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldEQ(FieldCheckinDate, v))
}

// CheckinDateNEQ applies the NEQ predicate on the "checkin_date" field.
func CheckinDateNEQ(v time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldNEQ(FieldCheckinDate, v))
}

// CheckinDateIn applies the In predicate on the "checkin_date" field.
func CheckinDateIn(vs ...time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldIn(FieldCheckinDate, vs...))
}

// CheckinDateNotIn applies the NotIn predicate on the "checkin_date" field.
func CheckinDateNotIn(vs ...time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldNotIn(FieldCheckinDate, vs...))
}

// CheckinDateGT applies the GT predicate on the "checkin_date" field.
func CheckinDateGT(v time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldGT(FieldCheckinDate, v))
}

// CheckinDateGTE applies the GTE predicate on the "checkin_date" field.
func CheckinDateGTE(v time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldGTE(FieldCheckinDate, v))
}

// CheckinDateLT applies the LT predicate on the "checkin_date" field.
func CheckinDateLT(v time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldLT(FieldCheckinDate, v))
}

// CheckinDateLTE applies the LTE predicate on the "checkin_date" field.
func CheckinDateLTE(v time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldLTE(FieldCheckinDate, v))
}

// RewardAmountEQ applies the EQ predicate on the "reward_amount" field.
func RewardAmountEQ(v float64) predicate.Checkin {
	return predicate.Checkin(sql.FieldEQ(FieldRewardAmount, v))
}

// RewardAmountNEQ applies the NEQ predicate on the "reward_amount" field.
func RewardAmountNEQ(v float64) predicate.Checkin {
	return predicate.Checkin(sql.FieldNEQ(FieldRewardAmount, v))
}

// RewardAmountIn applies the In predicate on the "reward_amount" field.
func RewardAmountIn(vs ...float64) predicate.Checkin {
	return predicate.Checkin(sql.FieldIn(FieldRewardAmount, vs...))
}

// RewardAmountNotIn applies the NotIn predicate on the "reward_amount" field.
func RewardAmountNotIn(vs ...float64) predicate.Checkin {
	return predicate.Checkin(sql.FieldNotIn(FieldRewardAmount, vs...))
}

// RewardAmountGT applies the GT predicate on the "reward_amount" field.
func RewardAmountGT(v float64) predicate.Checkin {
	return predicate.Checkin(sql.FieldGT(FieldRewardAmount, v))
}

// RewardAmountGTE applies the GTE predicate on the "reward_amount" field.
func RewardAmountGTE(v float64) predicate.Checkin {
	return predicate.Checkin(sql.FieldGTE(FieldRewardAmount, v))
}

// RewardAmountLT applies the LT predicate on the "reward_amount" field.
func RewardAmountLT(v float64) predicate.Checkin {
	return predicate.Checkin(sql.FieldLT(FieldRewardAmount, v))
}

// RewardAmountLTE applies the LTE predicate on the "reward_amount" field.
func RewardAmountLTE(v float64) predicate.Checkin {
	return predicate.Checkin(sql.FieldLTE(FieldRewardAmount, v))
}

// StreakDaysEQ applies the EQ predicate on the "streak_days" field.
func StreakDaysEQ(v int) predicate.Checkin {
	return predicate.Checkin(sql.FieldEQ(FieldStreakDays, v))
}

// StreakDaysNEQ applies the NEQ predicate on the "streak_days" field.
func StreakDaysNEQ(v int) predicate.Checkin {
	return predicate.Checkin(sql.FieldNEQ(FieldStreakDays, v))
}

// StreakDaysIn applies the In predicate on the "streak_days" field.
func StreakDaysIn(vs ...int) predicate.Checkin {
	return predicate.Checkin(sql.FieldIn(FieldStreakDays, vs...))
}

// StreakDaysNotIn applies the NotIn predicate on the "streak_days" field.
func StreakDaysNotIn(vs ...int) predicate.Checkin {
	return predicate.Checkin(sql.FieldNotIn(FieldStreakDays, vs...))
}

// StreakDaysGT applies the GT predicate on the "streak_days" field.
func StreakDaysGT(v int) predicate.Checkin {
	return predicate.Checkin(sql.FieldGT(FieldStreakDays, v))
}

// StreakDaysGTE applies the GTE predicate on the "streak_days" field.
func StreakDaysGTE(v int) predicate.Checkin {
	return predicate.Checkin(sql.FieldGTE(FieldStreakDays, v))
}

// StreakDaysLT applies the LT predicate on the "streak_days" field.
func StreakDaysLT(v int) predicate.Checkin {
	return predicate.Checkin(sql.FieldLT(FieldStreakDays, v))
}

// StreakDaysLTE applies the LTE predicate on the "streak_days" field.
func StreakDaysLTE(v int) predicate.Checkin {
	return predicate.Checkin(sql.FieldLTE(FieldStreakDays, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Checkin {
	return predicate.Checkin(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Checkin {
	return predicate.Checkin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Checkin {
	return predicate.Checkin(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Checkin) predicate.Checkin {
	return predicate.Checkin(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Checkin) predicate.Checkin {
	return predicate.Checkin(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Checkin) predicate.Checkin {
	return predicate.Checkin(sql.NotPredicates(p))
}
