// Code generated by ent, DO NOT EDIT.

package checkinblindboxrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the checkinblindboxrecord type in the database.
	Label = "checkin_blindbox_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPrizeItemID holds the string denoting the prize_item_id field in the database.
	FieldPrizeItemID = "prize_item_id"
	// FieldPrizeName holds the string denoting the prize_name field in the database.
	FieldPrizeName = "prize_name"
	// FieldRarity holds the string denoting the rarity field in the database.
	FieldRarity = "rarity"
	// FieldRewardType holds the string denoting the reward_type field in the database.
	FieldRewardType = "reward_type"
	// FieldRewardValue holds the string denoting the reward_value field in the database.
	FieldRewardValue = "reward_value"
	// FieldStreakDays holds the string denoting the streak_days field in the database.
	FieldStreakDays = "streak_days"
	// FieldRewardDetail holds the string denoting the reward_detail field in the database.
	FieldRewardDetail = "reward_detail"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the checkinblindboxrecord in the database.
	Table = "checkin_blindbox_records"
)

// Columns holds all SQL columns for checkinblindboxrecord fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldPrizeItemID,
	FieldPrizeName,
	FieldRarity,
	FieldRewardType,
	FieldRewardValue,
	FieldStreakDays,
	FieldRewardDetail,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPrizeName holds the default value on creation for the "prize_name" field.
	DefaultPrizeName string
	// DefaultRarity holds the default value on creation for the "rarity" field.
	DefaultRarity string
	// DefaultRewardType holds the default value on creation for the "reward_type" field.
	DefaultRewardType string
	// DefaultRewardValue holds the default value on creation for the "reward_value" field.
	DefaultRewardValue float64
	// DefaultStreakDays holds the default value on creation for the "streak_days" field.
	DefaultStreakDays int
	// DefaultRewardDetail holds the default value on creation for the "reward_detail" field.
	DefaultRewardDetail string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the CheckinBlindboxRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPrizeItemID orders the results by the prize_item_id field.
func ByPrizeItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeItemID, opts...).ToFunc()
}

// ByPrizeName orders the results by the prize_name field.
func ByPrizeName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeName, opts...).ToFunc()
}

// ByRarity orders the results by the rarity field.
func ByRarity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRarity, opts...).ToFunc()
}

// ByRewardType orders the results by the reward_type field.
func ByRewardType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardType, opts...).ToFunc()
}

// ByRewardValue orders the results by the reward_value field.
func ByRewardValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardValue, opts...).ToFunc()
}

// ByStreakDays orders the results by the streak_days field.
func ByStreakDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreakDays, opts...).ToFunc()
}

// ByRewardDetail orders the results by the reward_detail field.
func ByRewardDetail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardDetail, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
