// Code generated by ent, DO NOT EDIT.

package checkinblindboxrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldUserID, v))
}

// PrizeItemID applies equality check predicate on the "prize_item_id" field. It's identical to PrizeItemIDEQ.
func PrizeItemID(v int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldPrizeItemID, v))
}

// PrizeName applies equality check predicate on the "prize_name" field. It's identical to PrizeNameEQ.
func PrizeName(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldPrizeName, v))
}

// Rarity applies equality check predicate on the "rarity" field. It's identical to RarityEQ.
func Rarity(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldRarity, v))
}

// RewardType applies equality check predicate on the "reward_type" field. It's identical to RewardTypeEQ.
func RewardType(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldRewardType, v))
}

// RewardValue applies equality check predicate on the "reward_value" field. It's identical to RewardValueEQ.
func RewardValue(v float64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldRewardValue, v))
}

// StreakDays applies equality check predicate on the "streak_days" field. It's identical to StreakDaysEQ.
func StreakDays(v int) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldStreakDays, v))
}

// RewardDetail applies equality check predicate on the "reward_detail" field. It's identical to RewardDetailEQ.
func RewardDetail(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldRewardDetail, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLTE(FieldUserID, v))
}

// PrizeItemIDEQ applies the EQ predicate on the "prize_item_id" field.
func PrizeItemIDEQ(v int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldPrizeItemID, v))
}

// PrizeItemIDNEQ applies the NEQ predicate on the "prize_item_id" field.
func PrizeItemIDNEQ(v int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNEQ(FieldPrizeItemID, v))
}

// PrizeItemIDIn applies the In predicate on the "prize_item_id" field.
func PrizeItemIDIn(vs ...int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldIn(FieldPrizeItemID, vs...))
}

// PrizeItemIDNotIn applies the NotIn predicate on the "prize_item_id" field.
func PrizeItemIDNotIn(vs ...int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNotIn(FieldPrizeItemID, vs...))
}

// PrizeItemIDGT applies the GT predicate on the "prize_item_id" field.
func PrizeItemIDGT(v int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGT(FieldPrizeItemID, v))
}

// PrizeItemIDGTE applies the GTE predicate on the "prize_item_id" field.
func PrizeItemIDGTE(v int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGTE(FieldPrizeItemID, v))
}

// PrizeItemIDLT applies the LT predicate on the "prize_item_id" field.
func PrizeItemIDLT(v int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLT(FieldPrizeItemID, v))
}

// PrizeItemIDLTE applies the LTE predicate on the "prize_item_id" field.
func PrizeItemIDLTE(v int64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLTE(FieldPrizeItemID, v))
}

// PrizeNameEQ applies the EQ predicate on the "prize_name" field.
func PrizeNameEQ(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldPrizeName, v))
}

// PrizeNameNEQ applies the NEQ predicate on the "prize_name" field.
func PrizeNameNEQ(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNEQ(FieldPrizeName, v))
}

// PrizeNameIn applies the In predicate on the "prize_name" field.
func PrizeNameIn(vs ...string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldIn(FieldPrizeName, vs...))
}

// PrizeNameNotIn applies the NotIn predicate on the "prize_name" field.
func PrizeNameNotIn(vs ...string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNotIn(FieldPrizeName, vs...))
}

// PrizeNameGT applies the GT predicate on the "prize_name" field.
func PrizeNameGT(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGT(FieldPrizeName, v))
}

// PrizeNameGTE applies the GTE predicate on the "prize_name" field.
func PrizeNameGTE(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGTE(FieldPrizeName, v))
}

// PrizeNameLT applies the LT predicate on the "prize_name" field.
func PrizeNameLT(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLT(FieldPrizeName, v))
}

// PrizeNameLTE applies the LTE predicate on the "prize_name" field.
func PrizeNameLTE(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLTE(FieldPrizeName, v))
}

// PrizeNameContains applies the Contains predicate on the "prize_name" field.
func PrizeNameContains(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldContains(FieldPrizeName, v))
}

// PrizeNameHasPrefix applies the HasPrefix predicate on the "prize_name" field.
func PrizeNameHasPrefix(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldHasPrefix(FieldPrizeName, v))
}

// PrizeNameHasSuffix applies the HasSuffix predicate on the "prize_name" field.
func PrizeNameHasSuffix(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldHasSuffix(FieldPrizeName, v))
}

// PrizeNameEqualFold applies the EqualFold predicate on the "prize_name" field.
func PrizeNameEqualFold(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEqualFold(FieldPrizeName, v))
}

// PrizeNameContainsFold applies the ContainsFold predicate on the "prize_name" field.
func PrizeNameContainsFold(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldContainsFold(FieldPrizeName, v))
}

// RarityEQ applies the EQ predicate on the "rarity" field.
func RarityEQ(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldRarity, v))
}

// RarityNEQ applies the NEQ predicate on the "rarity" field.
func RarityNEQ(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNEQ(FieldRarity, v))
}

// RarityIn applies the In predicate on the "rarity" field.
func RarityIn(vs ...string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldIn(FieldRarity, vs...))
}

// RarityNotIn applies the NotIn predicate on the "rarity" field.
func RarityNotIn(vs ...string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNotIn(FieldRarity, vs...))
}

// RarityGT applies the GT predicate on the "rarity" field.
func RarityGT(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGT(FieldRarity, v))
}

// RarityGTE applies the GTE predicate on the "rarity" field.
func RarityGTE(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGTE(FieldRarity, v))
}

// RarityLT applies the LT predicate on the "rarity" field.
func RarityLT(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLT(FieldRarity, v))
}

// RarityLTE applies the LTE predicate on the "rarity" field.
func RarityLTE(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLTE(FieldRarity, v))
}

// RarityContains applies the Contains predicate on the "rarity" field.
func RarityContains(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldContains(FieldRarity, v))
}

// RarityHasPrefix applies the HasPrefix predicate on the "rarity" field.
func RarityHasPrefix(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldHasPrefix(FieldRarity, v))
}

// RarityHasSuffix applies the HasSuffix predicate on the "rarity" field.
func RarityHasSuffix(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldHasSuffix(FieldRarity, v))
}

// RarityEqualFold applies the EqualFold predicate on the "rarity" field.
func RarityEqualFold(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEqualFold(FieldRarity, v))
}

// RarityContainsFold applies the ContainsFold predicate on the "rarity" field.
func RarityContainsFold(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldContainsFold(FieldRarity, v))
}

// RewardTypeEQ applies the EQ predicate on the "reward_type" field.
func RewardTypeEQ(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldRewardType, v))
}

// RewardTypeNEQ applies the NEQ predicate on the "reward_type" field.
func RewardTypeNEQ(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNEQ(FieldRewardType, v))
}

// RewardTypeIn applies the In predicate on the "reward_type" field.
func RewardTypeIn(vs ...string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldIn(FieldRewardType, vs...))
}

// RewardTypeNotIn applies the NotIn predicate on the "reward_type" field.
func RewardTypeNotIn(vs ...string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNotIn(FieldRewardType, vs...))
}

// RewardTypeGT applies the GT predicate on the "reward_type" field.
func RewardTypeGT(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGT(FieldRewardType, v))
}

// RewardTypeGTE applies the GTE predicate on the "reward_type" field.
func RewardTypeGTE(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGTE(FieldRewardType, v))
}

// RewardTypeLT applies the LT predicate on the "reward_type" field.
func RewardTypeLT(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLT(FieldRewardType, v))
}

// RewardTypeLTE applies the LTE predicate on the "reward_type" field.
func RewardTypeLTE(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLTE(FieldRewardType, v))
}

// RewardTypeContains applies the Contains predicate on the "reward_type" field.
func RewardTypeContains(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldContains(FieldRewardType, v))
}

// RewardTypeHasPrefix applies the HasPrefix predicate on the "reward_type" field.
func RewardTypeHasPrefix(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldHasPrefix(FieldRewardType, v))
}

// RewardTypeHasSuffix applies the HasSuffix predicate on the "reward_type" field.
func RewardTypeHasSuffix(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldHasSuffix(FieldRewardType, v))
}

// RewardTypeEqualFold applies the EqualFold predicate on the "reward_type" field.
func RewardTypeEqualFold(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEqualFold(FieldRewardType, v))
}

// RewardTypeContainsFold applies the ContainsFold predicate on the "reward_type" field.
func RewardTypeContainsFold(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldContainsFold(FieldRewardType, v))
}

// RewardValueEQ applies the EQ predicate on the "reward_value" field.
func RewardValueEQ(v float64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldRewardValue, v))
}

// RewardValueNEQ applies the NEQ predicate on the "reward_value" field.
func RewardValueNEQ(v float64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNEQ(FieldRewardValue, v))
}

// RewardValueIn applies the In predicate on the "reward_value" field.
func RewardValueIn(vs ...float64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldIn(FieldRewardValue, vs...))
}

// RewardValueNotIn applies the NotIn predicate on the "reward_value" field.
func RewardValueNotIn(vs ...float64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNotIn(FieldRewardValue, vs...))
}

// RewardValueGT applies the GT predicate on the "reward_value" field.
func RewardValueGT(v float64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGT(FieldRewardValue, v))
}

// RewardValueGTE applies the GTE predicate on the "reward_value" field.
func RewardValueGTE(v float64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGTE(FieldRewardValue, v))
}

// RewardValueLT applies the LT predicate on the "reward_value" field.
func RewardValueLT(v float64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLT(FieldRewardValue, v))
}

// RewardValueLTE applies the LTE predicate on the "reward_value" field.
func RewardValueLTE(v float64) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLTE(FieldRewardValue, v))
}

// StreakDaysEQ applies the EQ predicate on the "streak_days" field.
func StreakDaysEQ(v int) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldStreakDays, v))
}

// StreakDaysNEQ applies the NEQ predicate on the "streak_days" field.
func StreakDaysNEQ(v int) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNEQ(FieldStreakDays, v))
}

// StreakDaysIn applies the In predicate on the "streak_days" field.
func StreakDaysIn(vs ...int) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldIn(FieldStreakDays, vs...))
}

// StreakDaysNotIn applies the NotIn predicate on the "streak_days" field.
func StreakDaysNotIn(vs ...int) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNotIn(FieldStreakDays, vs...))
}

// StreakDaysGT applies the GT predicate on the "streak_days" field.
func StreakDaysGT(v int) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGT(FieldStreakDays, v))
}

// StreakDaysGTE applies the GTE predicate on the "streak_days" field.
func StreakDaysGTE(v int) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGTE(FieldStreakDays, v))
}

// StreakDaysLT applies the LT predicate on the "streak_days" field.
func StreakDaysLT(v int) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLT(FieldStreakDays, v))
}

// StreakDaysLTE applies the LTE predicate on the "streak_days" field.
func StreakDaysLTE(v int) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLTE(FieldStreakDays, v))
}

// RewardDetailEQ applies the EQ predicate on the "reward_detail" field.
func RewardDetailEQ(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldRewardDetail, v))
}

// RewardDetailNEQ applies the NEQ predicate on the "reward_detail" field.
func RewardDetailNEQ(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNEQ(FieldRewardDetail, v))
}

// RewardDetailIn applies the In predicate on the "reward_detail" field.
func RewardDetailIn(vs ...string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldIn(FieldRewardDetail, vs...))
}

// RewardDetailNotIn applies the NotIn predicate on the "reward_detail" field.
func RewardDetailNotIn(vs ...string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNotIn(FieldRewardDetail, vs...))
}

// RewardDetailGT applies the GT predicate on the "reward_detail" field.
func RewardDetailGT(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGT(FieldRewardDetail, v))
}

// RewardDetailGTE applies the GTE predicate on the "reward_detail" field.
func RewardDetailGTE(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGTE(FieldRewardDetail, v))
}

// RewardDetailLT applies the LT predicate on the "reward_detail" field.
func RewardDetailLT(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLT(FieldRewardDetail, v))
}

// RewardDetailLTE applies the LTE predicate on the "reward_detail" field.
func RewardDetailLTE(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLTE(FieldRewardDetail, v))
}

// RewardDetailContains applies the Contains predicate on the "reward_detail" field.
func RewardDetailContains(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldContains(FieldRewardDetail, v))
}

// RewardDetailHasPrefix applies the HasPrefix predicate on the "reward_detail" field.
func RewardDetailHasPrefix(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldHasPrefix(FieldRewardDetail, v))
}

// RewardDetailHasSuffix applies the HasSuffix predicate on the "reward_detail" field.
func RewardDetailHasSuffix(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldHasSuffix(FieldRewardDetail, v))
}

// RewardDetailIsNil applies the IsNil predicate on the "reward_detail" field.
func RewardDetailIsNil() predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldIsNull(FieldRewardDetail))
}

// RewardDetailNotNil applies the NotNil predicate on the "reward_detail" field.
func RewardDetailNotNil() predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNotNull(FieldRewardDetail))
}

// RewardDetailEqualFold applies the EqualFold predicate on the "reward_detail" field.
func RewardDetailEqualFold(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEqualFold(FieldRewardDetail, v))
}

// RewardDetailContainsFold applies the ContainsFold predicate on the "reward_detail" field.
func RewardDetailContainsFold(v string) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldContainsFold(FieldRewardDetail, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CheckinBlindboxRecord) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CheckinBlindboxRecord) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CheckinBlindboxRecord) predicate.CheckinBlindboxRecord {
	return predicate.CheckinBlindboxRecord(sql.NotPredicates(p))
}
